apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-m34
  namespace: ns-challenges
  labels:
    app: m34-deploy
    challenge-id: ${CHALLENGE_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m34-deploy
      challenge-id: ${CHALLENGE_ID}
  template:
    metadata:
      labels:
        app: m34-deploy
        challenge-id: ${CHALLENGE_ID}
    spec:
      containers:
      - name: nginx
        image: nginx:broken-tag
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"
