apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ns-challenges
  labels:
    app: config-mount
    challenge-id: ${CHALLENGE_ID}
data:
  APP_ENV: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-mount
  namespace: ns-challenges
  labels:
    app: config-mount
    challenge-id: ${CHALLENGE_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-mount
      challenge-id: ${CHALLENGE_ID}
  template:
    metadata:
      labels:
        app: config-mount
        challenge-id: ${CHALLENGE_ID}
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh", "-c", "if [ \"$(cat /config/APP_ENV)\" = \"production\" ]; then while true; do sleep 3600; done; else exit 1; fi"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: app-config
