apiVersion: apps/v1
kind: Deployment
metadata:
  name: zombie-process
  namespace: ns-challenges
  labels:
    app: zombie-process
    challenge-id: ${CHALLENGE_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zombie-process
      challenge-id: ${CHALLENGE_ID}
  template:
    metadata:
      labels:
        app: zombie-process
        challenge-id: ${CHALLENGE_ID}
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /app
            echo 'while true; do sleep 1; done' > /app/rogue.sh
            chmod +x /app/rogue.sh
            /app/rogue.sh &
            while true; do sleep 3600; done
