apiVersion: v1
data:
  NODE_ENV: production
  PORT: "4000"
  POSTGRES_DB: devopsarena
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis-service:6379
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"NODE_ENV":"production","PORT":"4000","POSTGRES_DB":"devopsarena","POSTGRES_HOST":"postgres-service","POSTGRES_PORT":"5432","REDIS_HOST":"redis-service","REDIS_PORT":"6379","REDIS_URL":"redis://redis-service:6379"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-config","namespace":"ns-devops-arena"}}
  creationTimestamp: "2026-08-08T11:18:22Z"
  name: app-config
  namespace: ns-devops-arena
  resourceVersion: "13256"
  uid: 2bcf5b43-f7eb-4b8e-bb95-57468cf3e0a2
