apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: ns-devops-arena
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-role
  namespace: ns-devops-arena
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "batch"]
  resources: ["deployments", "services", "ingress", "configmaps", "secrets", "persistentvolumeclaims", "pods", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: ns-devops-arena
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: ns-devops-arena
roleRef:
  kind: Role
  name: jenkins-deployer-role
  apiGroup: rbac.authorization.k8s.io
