apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ns-devops-arena
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-sandbox-manager
rules:
  # Allow managing namespaces and all resources in required API groups (needed to grant sandbox-role)
  - apiGroups: ["", "apps", "networking.k8s.io", "batch", "extensions"]
    resources: ["*"]
    verbs: ["*"]
  # Allow managing RBAC for the sandbox (with escalate to allow granting RBAC perms)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "bind", "escalate"]
  # Allow namespace management
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-sandbox-manager-binding
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: ns-devops-arena
roleRef:
  kind: ClusterRole
  name: backend-sandbox-manager
  apiGroup: rbac.authorization.k8s.io
